/**
 * THE LICENCE NOTICE HAS TO REACH THE ARTEFACT.
 *
 * MIT, BSD-2/3 and Apache-2.0 all require their copyright notice and licence
 * text to ACCOMPANY distributions. Every GetVect binary published before this
 * carried none — not one licence file, not even Electron's own — because
 * `files:` excludes `node_modules/**` and `extraResources` shipped a single
 * icon. The repo looked fine; the artefact was the thing out of compliance.
 *
 * That is why these are config assertions rather than a unit test. Each failure
 * below is invisible in development and only shows up in a shipped binary
 * nobody re-opens:
 *
 *   - drop the extraResources entry and the notice stops shipping while
 *     everything still builds and runs;
 *   - drop it from `build` and it stops being regenerated, so it silently
 *     describes an older dependency tree — correct-looking and wrong, which is
 *     worse than absent;
 *   - let the generator become hand-maintained and it is right once.
 *
 * The generator's own failure modes (empty output, an undeterminable licence, a
 * harness-only native module reaching the shipped set) are enforced inside the
 * script, which fails the build rather than emitting a thin file.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const read = (p) => readFileSync(join(root, p), 'utf8');

test('the notice is shipped inside the app, not left in the repo', () => {
  const yml = read('electron-builder.yml');
  assert.match(
    yml,
    /extraResources:[\s\S]*?- from: build\/third-party\b/,
    'electron-builder.yml no longer ships build/third-party — a notice that exists only ' +
      'in the repository does not accompany the distribution',
  );
  assert.match(yml, /to: third-party/, 'the notice must land at Resources/third-party');
});

test('the notice is regenerated by the build, never hand-maintained', () => {
  const pkg = JSON.parse(read('package.json'));
  assert.match(
    pkg.scripts.build,
    /npm run notices/,
    '`build` no longer runs the notice generator: the shipped notice would keep ' +
      'describing whatever dependency tree existed when someone last ran it by hand',
  );
  assert.match(pkg.scripts.notices, /generate-third-party-notices\.mjs/);
});

test('the generator derives its list from the bundle, not from package.json', () => {
  // package.json overstates what ships: sharp and @resvg/resvg-js are declared
  // dependencies whose code is excluded from the artefact on purpose. A
  // generator that read the manifest would claim to redistribute software it
  // does not, which is its own kind of false statement.
  const gen = read('scripts/generate-third-party-notices.mjs');
  assert.match(gen, /electron-updater\.meta\.json/, 'the esbuild metafile is the source of truth');
  assert.match(gen, /MUST_NOT_SHIP/, 'the harness-only modules must be asserted absent, not assumed');

  const bundler = read('scripts/bundle-updater.mjs');
  assert.match(
    bundler,
    /metafile:\s*true/,
    'bundle-updater no longer emits a metafile, so the notice has nothing authoritative to read',
  );
});

test('Electron and Chromium licences ship too', () => {
  const gen = read('scripts/generate-third-party-notices.mjs');
  // Chromium's notice is ~20 MB and required. Size is not an exemption, so the
  // generator hard-fails if it is missing rather than quietly skipping it.
  assert.match(gen, /LICENSES\.chromium\.html/);
  assert.match(gen, /dist', 'LICENSE'|dist\/LICENSE/);
});

test('the About panel names the licence beside the copyright', () => {
  const main = read('src/main/main.ts');
  const copyright = /copyright:\s*'([^']+)'/.exec(main);
  assert.ok(copyright, 'the About panel no longer sets a copyright line');
  assert.match(
    copyright[1],
    /MIT/,
    'a bare © with no licence named reads as all-rights-reserved to a reader who does ' +
      'not already know — which is exactly the reader this project wants to reach',
  );
  assert.match(main, /installLicenceMenu\(\)/, 'the notice must be reachable, not merely present');
});
